### ISSUE TITLE
CTRL + ALT + SHIFT + U doing class diagram

### ISSUE THREAD

**Issue by nathan3882** [Stefku/intellij-reference-diagram#62]
Hi there,

I installed the plugin for the first time yesterday and it worked fine - but it seems to have broken since then - when I press the short cut CTRL + ALT + SHIFT + U it to jumps straight to the default IntelliJ Class Diagram generator - was wondering if you had any ideas as to what I could do - is there a way to directly generate it? 

Thanks and great plugin 🥇

**Comment by Stefku** [comment]
Hi @nathan3882, sorry for the late reply.

The reference diagram represents exactly one class. Thus, you have to put the cursor into the class you want to visualize. If you select a file in the project pane then the plugin does not know what class is meant, because one java file can have more than one class definition.

A better way would be to ask the user what class should be used if a java file does contain more than one class. But currently, I don't have time to implement this.

Cheers
Stefku
